
package com.philps.soapws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContactsService", targetNamespace = "http://philps.com/soapws/", wsdlLocation = "http://localhost:8080/mywebapp/ws/contacts-webservice?wsdl")
public class ContactsService
    extends Service
{

    private final static URL CONTACTSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTACTSSERVICE_EXCEPTION;
    private final static QName CONTACTSSERVICE_QNAME = new QName("http://philps.com/soapws/", "ContactsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/mywebapp/ws/contacts-webservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTACTSSERVICE_WSDL_LOCATION = url;
        CONTACTSSERVICE_EXCEPTION = e;
    }

    public ContactsService() {
        super(__getWsdlLocation(), CONTACTSSERVICE_QNAME);
    }

    public ContactsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTACTSSERVICE_QNAME, features);
    }

    public ContactsService(URL wsdlLocation) {
        super(wsdlLocation, CONTACTSSERVICE_QNAME);
    }

    public ContactsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTACTSSERVICE_QNAME, features);
    }

    public ContactsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContactsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContactsServiceSoap
     */
    @WebEndpoint(name = "ContactsServiceSoap")
    public ContactsServiceSoap getContactsServiceSoap() {
        return super.getPort(new QName("http://philps.com/soapws/", "ContactsServiceSoap"), ContactsServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContactsServiceSoap
     */
    @WebEndpoint(name = "ContactsServiceSoap")
    public ContactsServiceSoap getContactsServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://philps.com/soapws/", "ContactsServiceSoap"), ContactsServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTACTSSERVICE_EXCEPTION!= null) {
            throw CONTACTSSERVICE_EXCEPTION;
        }
        return CONTACTSSERVICE_WSDL_LOCATION;
    }

}
